# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "BigInt" = "sha256-mMR7Jg7Jm6jqXzt+neo/N1SzWjbI/Fi6dAufMhbf9MU=";
    "Defile" = "sha256-XGTLBqtkKFZg+sVCUEWPyLB4YJZ/cY6n4iGxe1fA+Ws=";
    "PythonKit" = "sha256-W5O1lglezaFOoIgIGBAVo1OobXDZwpx0ZO67PSE4A5E=";
    "swift-argument-parser" = "sha256-qEJ329hqQyQVxtHScD7qPmWW9ZDf9bX+4xgpDlX0w5A=";
    "swift-collections" = "sha256-WNj19mRvDSZNcDzZvmtS+jZxngBooiHekh3IsPZnKUQ=";
    "Yams" = "sha256-AY/fIvB7THrl9GWzGJL8eDBbkcLw27tSRTGtUqmYw8k=";
  };
}
