# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "BigInt" = "1iglvwb357qbfjx5iz686rdb6m1p7zm9szivbzmai6y91qk7pi4q";
    "CommandLine" = "134cc70zvj60jfkxd8vpg2ifgl796a4yvvdd28hpxf007p1184rs";
    "Defile" = "0szrq1bppc91wakqwwbzjrh7ic68ix2m0hn5z9h5ca34mc3cnr2w";
    "PythonKit" = "18211q88wcpf7qq7vq7ilchdmgjd9lmx7dpq4s41bb48kds5gshm";
    "swift-collections" = "0i19czvb1j0xjbg238k802g72dpsa9mvxn9wf16jc3bgckvgbn2q";
    "Yams" = "1jf3k2lm5b9i8m9bpnzhqa8mnc3qzj91icv5ykjplk3vy0idz3q1";
  };
}
