on:
  push:
    tags:
      - "*"

name: AppImage

jobs:
  build_appimage:
    name: Build AppImage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: |
          export VERSION_NUM=$(ruby -e "print '$GITHUB_REF'.split('/')[2]")
          echo ::set-output name=value::${VERSION_NUM}
      - name: Build
        run: |
          cd appimage
          export FAULT_IMAGE_NAME=ghcr.io/aucohl/fault:${{ steps.get_version.outputs.value }}
          make
      - name: Test AppImage
        run: |
          ./appimage/Fault-x86_64.AppImage smoke-test
      - name: Copy AppImage
        run: |
          cp ./appimage/Fault-x86_64.AppImage /tmp/Fault-${{ steps.get_version.outputs.value }}-x86_64.AppImage
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/Fault-${{ steps.get_version.outputs.value }}-x86_64.AppImage
