on:
  push:
    tags:
      - "*"

name: CI

jobs:
  build_image:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Tag
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        echo TAG="$(ruby -e "print '$GITHUB_REF'.split('/')[2]")" >> $GITHUB_ENV
    - name: Build Images
      run: |
        docker build -t cloud-v/fault:latest .
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GHCR
      run: |
        docker image tag cloud-v/fault:latest ghcr.io/cloud-v/fault:latest
        docker image tag cloud-v/fault:latest ghcr.io/cloud-v/fault:$TAG
        docker push ghcr.io/cloud-v/fault:$TAG
        docker push ghcr.io/cloud-v/fault:latest

