name: CI
# Events that trigger workflow
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  test:
    name: Test/Nix
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build
  push_to_pypi:
    name: Build
    needs: [test]
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set default for env.NEW_TAG
        run: echo "NEW_TAG=NO_NEW_TAG" >> $GITHUB_ENV
      - name: Check for new version
        if: ${{ env.BRANCH_NAME == 'main' }}
        run: |
          python3 .github/scripts/generate_tag.py
      - name: Tag Commit
        if: ${{ env.NEW_TAG != 'NO_NEW_TAG' }}
        uses: tvdias/github-tagger@v0.0.1
        with:
          tag: "${{ env.NEW_TAG }}"
          repo-token: "${{ secrets.MY_TOKEN }}"
