name: Nix
# Events that trigger workflow
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  test:
    name: Build and Test with Nix
    runs-on: macos-14 # fastest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://openlane.cachix.org
            extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
